/* Auto-generated by DimOS ArduinoModule — do not edit */
#ifndef DIMOS_ARDUINO_H
#define DIMOS_ARDUINO_H

/* --- Config --- */
#define DIMOS_BAUDRATE 115200

/* --- Topic enum (shared with C++ bridge) --- */
enum dimos_topic {
    DIMOS_TOPIC_DEBUG = 0,
    DIMOS_TOPIC__LED_CMD = 1,  /* In[Bool] */
    DIMOS_TOPIC__LED_STATE = 2,  /* Out[Bool] */
};

/* --- Message type headers --- */
#include "std_msgs/Bool.h"

/* --- DSP protocol core --- */
#include "dsp_protocol.h"

#endif /* DIMOS_ARDUINO_H */
